version: '3'
services:
 raspbian_lab:
  build: .
  image: raspbian_lab:latest
  container_name: rasptracking
  volumes:
   - /tmp/.X11-unix/:/tmp/.X11-unix
   - /home/pi/Desktop/datos_practicas:/home/pi/dataGPI
  environment:
   - DISPLAY=$DISPLAY
  privileged: true
  stdin_open: true
  tty: true
